<h3><center>Applied Data Mining (2021-22)</center></h3>
<h1><center>Lab 1: Introduction to data mining with Python- Instalation</center></h1>


The objective of the first lab is to introduce a couple of machine learning tools and libraries that are going to be used during this course. We will use **Python** as our programming language, **Anaconda** as our virtual emvironment and package manager, and finally **Jupyter notebook** as our development environment. Note that this lab is not intended to teach python programming. So, it is recommended to have some python programming background.

Please follow the following steps to prepare the development environment:
- Download Anaconda from https://www.anaconda.com/distribution/, and install it on your machine.
- Create an environment with Python 3.7 and use `ADM_course` as the environment name. You can find information about creating and managing anaconda environments using navigator interface from https://docs.anaconda.com/anaconda/navigator/tutorials/manage-environments/#creating-a-new-environment. You can also do it through shell commands https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html. Here is a list of useful commands:
    - `conda create -n ADM_course python=3.7`
    - `conda env list`
    - `source activate ADM_course`
- Use Anaconda navigator to install Jupyter. To do so, first go to the Home tab, then select ADM&DS_course environment. Finally, from the list of applications, find Jupyter Notebook and install it. 
- Now you should be able to launch Jupyter. This will launch a new browser window (or a new tab) showing the Notebook Dashboard, a sort of control panel that allows (among other things) to select which notebook to open. You can also launch Jupyter using shell command. To do so, first activate `ADM_course` environment, then run the following command: `jupyter notebook`
- To run our first program, please open ADM&DS_Lab1.ipynb file using Jupyter. You can find the rest of the instructions on the file.
- Picture below shows Notebook user interface:
<img src="files/jupyter screenshot 1.png" alt="Drawing" style="width: 500px;">
- Play with the interface and try to figure out its functionalities. You can find lots of useful information about Notebook from the following [link](https://buildmedia.readthedocs.org/media/pdf/jupyter-notebook/latest/jupyter-notebook.pdf).

### First program in Jupyter
- Change the Jupyter Notebook folder to whatever folder you have your codes on
- Open `ADM_Lab1.ipynb` and run the following line of code:

In [1]:
print("Hi, World!")

Hi, World!


### Installing python libraries using jupyter
In this section you will learn how to install a package using jupyter. We start by installing `Numpy`. Numpy is the most basic and a powerful package for scientific computing and data manipulation in python. There are two ways to install a python package.
#### a) conda package
Use the following piece of code to install desired python packages. Make sure to change channel (in this case `anaconda`) and name of the package (in this case `numpy`) based on what you want to install.

In [2]:
# Install a conda package in the current Jupyter kernel
import sys
!conda install --yes --prefix {sys.prefix} -c anaconda numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Naing\anaconda3\envs\ADM_course

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB  anaconda
    ca-certificates-2020.10.14 |                0         159 KB  anaconda
    certifi-2020.6.20          |           py37_0         160 KB  anaconda
    intel-openmp-2020.2        |              254         2.0 MB  anaconda
    mkl-2019.4                 |              245       157.5 MB  anaconda
    mkl-service-2.3.0          |   py37hb782905_0         200 KB  anaconda
    mkl_fft-1.2.0              |   py37h45dec08_0         135 KB  anaconda
    mkl_random-1.0.4           |   py37h343c172_0         287 KB



==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda





    numpy-1.19.1               |   py37h5510c5b_0          21 KB  anaconda
    numpy-base-1.19.1          |   py37ha3acd2a_0         4.9 MB  anaconda
    ------------------------------------------------------------
                                           Total:       165.3 MB

The following NEW packages will be INSTALLED:

  blas               anaconda/win-64::blas-1.0-mkl
  intel-openmp       anaconda/win-64::intel-openmp-2020.2-254
  mkl                anaconda/win-64::mkl-2019.4-245
  mkl-service        anaconda/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            anaconda/win-64::mkl_fft-1.2.0-py37h45dec08_0
  mkl_random         pkgs/r/win-64::mkl_random-1.0.4-py37h343c172_0
  numpy              anaconda/win-64::numpy-1.19.1-py37h5510c5b_0
  numpy-base         anaconda/win-64::numpy-base-1.19.1-py37ha3acd2a_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.10.26~ --> anaconda::ca-certificate

#### b) pip package
You can also use pip for installing the packages. However, it is recommended to do it by conda package manger rather than pip. To install a package using pip use the following piece of code.

In [3]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy

### Introduction to Numpy
If you are going to work on data analysis or machine learning projects, then having a solid understanding of numpy is nearly mandatory. Specially since other packages for data analysis (like pandas) is built on top of numpy and the scikit-learn package which is used to build machine learning applications works heavily with numpy as well.

So what does numpy provide?

At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays.

In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations.
To understand this better, let’s first see how to create a numpy array.

In [4]:
# Create a 1d array from a list
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not. That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.
So, that’s about 1d array. You can also pass a list of lists to create a matrix like a 2d array.

In [5]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Finally, you can always convert an array back to a python list using tolist().

In [6]:
# Convert an array back to a list
arr2d.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

### How to inspect the size and shape of a numpy array?
Every array has some properties to inspect its structure. Here is a list of questions about arrays and how we can answer them:
> <li>If it is a 1D or a 2D array or more. (ndim)</li>
> <li>How many items are present in each dimension (shape)</li>
> <li>What is its datatype (dtype)</li>
> <li>What is the total number of items in it (size)</li>
> <li>Samples of first few items in the array (through indexing)</li>

In [8]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [9]:
# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2


### How to access specific items from an array?

In [22]:
print('Extract a specific item by index')
print(arr2[1,1])

print('Extract the first 2 rows and columns')
print(arr2[:2, :2])

print('Extract the last row and column')
print(arr2[-2,-2])

print(arr2)

Extract a specific item by index
4.0
Extract the first 2 rows and columns
[[1. 2.]
 [3. 4.]]
Extract the last row and column
5.0
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [5. 6. 7. 8.]]


In [21]:
arr2[-1,-4]

5.0

### How to compute average, min, max, variance on the ndarray?

In [8]:
# mean, max, min, and variance
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())
print("Variance value is: ", arr2.var())

Mean value is:  4.5
Max value is:  8.0
Min value is:  1.0
Variance value is:  3.9166666666666665


### How to create a new array from an existing array?
If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory.
That means, if you make any changes to the new array, it will reflect in the parent array as well.
So to avoid disturbing the parent array, you need to make a copy of it using `copy()`. All numpy arrays come with the `copy()` method.

In [14]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
arr2a[1, 1] = 100  # 100 will reflect in arr2
arr2

array([[  1.,   2.,   3.,   4.],
       [  3., 100.,   5.,   6.],
       [  5.,   6.,   7.,   8.]])

In [15]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[1, 1] = 101  # 101 will not reflect in arr2
arr2

array([[  1.,   2.,   3.,   4.],
       [  3., 100.,   5.,   6.],
       [  5.,   6.,   7.,   8.]])

### How to generate random numbers?
The `random` module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.

In [16]:
print('Random numbers between [0,1) of shape 2,2')
print(np.random.rand(2,2))

print('Normal distribution with mean=0 and variance=1 of shape 2,2')
print(np.random.randn(2,2))

print('Random integers between [0, 10) of shape 2,2')
print(np.random.randint(0, 10, size=[2,2]))

print('One random number between [0,1)')
print(np.random.random())

print('Random numbers between [0,1) of shape 2,2')
print(np.random.random(size=[2,2]))

print('Pick 10 items from a given list, with equal probability')
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

print('Pick 10 items from a given list with a predefined probability \'p\'')
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

Random numbers between [0,1) of shape 2,2
[[0.00482472 0.0974771 ]
 [0.77546084 0.60609847]]
Normal distribution with mean=0 and variance=1 of shape 2,2
[[-0.49931307 -0.65226717]
 [ 0.24188207 -2.60915332]]
Random integers between [0, 10) of shape 2,2
[[3 2]
 [4 2]]
One random number between [0,1)
0.1557443090616697
Random numbers between [0,1) of shape 2,2
[[0.19840699 0.87526976]
 [0.09857304 0.56929571]]
Pick 10 items from a given list, with equal probability
['e' 'o' 'o' 'e' 'u' 'i' 'u' 'o' 'a' 'e']
Pick 10 items from a given list with a predefined probability 'p'
['a' 'e' 'i' 'o' 'o' 'a' 'e' 'a' 'i' 'a']


### How to do simple operations on array?
We have demonstrated how to create and change Arrays. Now, we want to show how we can perform basic arithmetics with NumPy module. The arithemtic standard Operators `+`, `-`, `*`, `/`, `**`, `%` are applied on the elements, this means that the arrays have to have the same size.

In [17]:
# standard Operators
x = np.array([1,5,2])
print('x: {}'.format(x))
y = np.array([7,4,1])
print('y: {}'.format(y))
print('x + y')
print(x + y)
print('x - y')
print(x - y)
print('x * y')
print(x * y)
print('x / y')
print(x / y)
print('x ** y')
print(x ** y)
print('x % y')
print(x % y) # modulo

x: [1 5 2]
y: [7 4 1]
x + y
[8 9 3]
x - y
[-6  1  1]
x * y
[ 7 20  2]
x / y
[0.14285714 1.25       2.        ]
x ** y
[  1 625   2]
x % y
[1 1 0]


In [18]:
# Vector Addition and Subtraction
z = x + y
z

array([8, 9, 3])

In [19]:
# Dot Product
z = np.dot(x,y)
z

29

In [20]:
# Cross Product
x = np.array([0,1])
y = np.array([1,0])
z = np.cross(x,y)
z

array(-1)

In [23]:
# 2d array
a = np.array([[1, 0],[0, 1]])
print('a:')
display(a)
b = np.array([[4, 1],[2, 2]])
print('b:')
b

a:


array([[1, 0],
       [0, 1]])

b:


array([[4, 1],
       [2, 2]])

In [24]:
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [25]:
a * b

array([[4, 0],
       [0, 2]])