<h3><center>Applied Data Mining</center></h3>
<h1><center>Lab 2: Data Preparation</center></h1>


The objective of the second lab is to implement some of the methods that we have covered in the lecture to prepare the data for the modeling part. In this lab, you also have some tasks to do. 


### Download and Import Data
The examples provided in this lab will use the following datasets. Download them and store them on the same path as your notebook is.
- __Building permits__: A building permit is an official approval document issued by a governmental agency that allows you or your contractor to proceed with a construction or remodeling project on one's property. To get more information about this dataset look [here](https://www.kaggle.com/aparnashastry/building-permit-applications-data)
- __Iris dataset__: gives the measurements in centimeters of the variables sepal length and width and petal length and width for 150 iris flowers from three different species. Download data from blackboard or [here](https://www.kaggle.com/saurabh00007/iriscsv/download)
- __AUS weather dataset__: The data set contains daily weather observations from numerous Australian weather stations. The target variable RainTomorrow means: Did it rain the next day? Yes or No. Download data from blackboard.

- __NSL_KDD dataset__: contains a standard set of data to be audited, which includes a wide variety of intrusions simulated in a military network environment. You can download this data from blackboard. To get more information about this dataset look [here](https://www.unb.ca/cic/datasets/nsl.html)

Download data from blackboard or [here](https://drive.google.com/open?id=1bYwUzFzrgCJ1lyjFVf3f4nyatBaMlcxS)
<img src="sepal vs petal.jpeg" />

    Using the below codes you can import the data and see some information about the data:
   

In [20]:
# modules we'll use
import pandas as pd
import numpy as np
import os
pd.options.mode.chained_assignment = None  # default='warn'

mydata_bpermits = pd.read_csv('lab2_data/Building_Permits.csv',low_memory=False)
mydata_bpermits.head()
mydata_bpermits.info()

print('Hi')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype  
---  ------                                  --------------   -----  
 0   Permit Number                           198900 non-null  object 
 1   Permit Type                             198900 non-null  int64  
 2   Permit Type Definition                  198900 non-null  object 
 3   Permit Creation Date                    198900 non-null  object 
 4   Block                                   198900 non-null  object 
 5   Lot                                     198900 non-null  object 
 6   Street Number                           198900 non-null  int64  
 7   Street Number Suffix                    2216 non-null    object 
 8   Street Name                             198900 non-null  object 
 9   Street Suffix                           196132 non-null  object 
 10  Unit                                    2947

In [4]:
mydata_bpermits.head()

Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect   
1  201604195146            4                      sign - erect   
2  201605278609            3  additions alterations or repairs   
3  201611072166            8            otc alterations permit   
4  201611283529            6                       demolitions   

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                  NaN   
1           04/19/2016  0306  007            440                  NaN   
2           05/27/2016  0595  203           1647                  NaN   
3           11/07/2016  0156  011           1230                  NaN   
4           11/28/2016  0342  001            950                  NaN   

  Street Name Street Suffix  ...  Existing Construction Type  \
0       Ellis            St  ...                         3.0   
1       Geary            St  ...                         3.0   
2     Pacific            Av  ...                         1.0   
3     Pacific            Av  ...                         5.0   
4      Market            St  ...                         3.0   

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                        NaN   
1                          constr type 3                        NaN   
2                          constr type 1                        1.0   
3                         wood frame (5)                        5.0   
4                          constr type 3                        NaN   

  Proposed Construction Type Description Site Permit Supervisor District  \
0                                    NaN         NaN                 3.0   
1                                    NaN         NaN                 3.0   
2                          constr type 1         NaN                 3.0   
3                         wood frame (5)         NaN                 3.0   
4                                    NaN         NaN                 6.0   

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0   
1                          Tenderloin  94102.0   
2                        Russian Hill  94109.0   
3                            Nob Hill  94109.0   
4                          Tenderloin  94102.0   

                                    Location      Record ID  
0  (37.785719256680785, -122.40852313194863)  1380611233945  
1   (37.78733980600732, -122.41063199757738)  1420164406718  
2    (37.7946573324287, -122.42232562979227)  1424856504716  
3   (37.79595867909168, -122.41557405519474)  1443574295566  
4   (37.78315261897309, -122.40950883997789)   144548169992  

[5 rows x 43 columns]


### Handling Missing Values
First, we need to make sure that whether the data consists missing values or not?

   

In [21]:
mydata_bpermits.isnull().count()

Permit Number                             198900
Permit Type                               198900
Permit Type Definition                    198900
Permit Creation Date                      198900
Block                                     198900
Lot                                       198900
Street Number                             198900
Street Number Suffix                      198900
Street Name                               198900
Street Suffix                             198900
Unit                                      198900
Unit Suffix                               198900
Description                               198900
Current Status                            198900
Current Status Date                       198900
Filed Date                                198900
Issued Date                               198900
Completed Date                            198900
First Construction Document Date          198900
Structural Notification                   198900
Number of Existing S


#### Using the below code you find the features which have missing values..   

In [22]:
mydata_bpermits.shape

vars_with_missing = []

for f in mydata_bpermits.columns:
    #missings = mydata[f].isnull().count()
    missings = sum(mydata_bpermits[f].isnull())
    if missings > 0:
        vars_with_missing.append(f)
        missings_perc = missings/mydata_bpermits.shape[0]
        
        print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))
        
print('In total, there are {} variables with missing values'.format(len(vars_with_missing)))


Variable Street Number Suffix has 196684 records (98.89%) with missing values
Variable Street Suffix has 2768 records (1.39%) with missing values
Variable Unit has 169421 records (85.18%) with missing values
Variable Unit Suffix has 196939 records (99.01%) with missing values
Variable Description has 290 records (0.15%) with missing values
Variable Issued Date has 14940 records (7.51%) with missing values
Variable Completed Date has 101709 records (51.14%) with missing values
Variable First Construction Document Date has 14946 records (7.51%) with missing values
Variable Structural Notification has 191978 records (96.52%) with missing values
Variable Number of Existing Stories has 42784 records (21.51%) with missing values
Variable Number of Proposed Stories has 42868 records (21.55%) with missing values
Variable Voluntary Soft-Story Retrofit has 198865 records (99.98%) with missing values
Variable Fire Only Permit has 180073 records (90.53%) with missing values
Variable Permit Expirat

## Data Cleaning
### Removing Missing Values
Try to remove the features which have many missing values!

   

In [23]:
category_with_missing = []
missings = 0

for f in mydata_bpermits:
    #missings = mydata[f].isnull().count()
    missings = sum(mydata_bpermits[f].isnull())
    if missings > 0:
        vars_with_missing.append(f)
        missings_perc = missings/mydata_bpermits.shape[0]
        
        print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))

mydata_bpermits=mydata_bpermits.drop(['Street Number Suffix','Fire Only Permit'],axis=1)


Variable Street Number Suffix has 196684 records (98.89%) with missing values
Variable Street Suffix has 2768 records (1.39%) with missing values
Variable Unit has 169421 records (85.18%) with missing values
Variable Unit Suffix has 196939 records (99.01%) with missing values
Variable Description has 290 records (0.15%) with missing values
Variable Issued Date has 14940 records (7.51%) with missing values
Variable Completed Date has 101709 records (51.14%) with missing values
Variable First Construction Document Date has 14946 records (7.51%) with missing values
Variable Structural Notification has 191978 records (96.52%) with missing values
Variable Number of Existing Stories has 42784 records (21.51%) with missing values
Variable Number of Proposed Stories has 42868 records (21.55%) with missing values
Variable Voluntary Soft-Story Retrofit has 198865 records (99.98%) with missing values
Variable Fire Only Permit has 180073 records (90.53%) with missing values
Variable Permit Expirat

In [24]:
mydata_bpermits.shape


(198900, 41)


#### Removing Missing Values
You can even remove all the columns which have missing values

   

In [25]:
mytestdata=mydata_bpermits.copy()
mytestdata=mytestdata.dropna(axis=1)
mytestdata.shape

(198900, 12)

Filling missing values with Mean and Mode. We apply these two methods on two numrical features as follows:   
   

In [26]:
newcolumns=mydata_bpermits[['Zipcode','Revised Cost']]
#Mean
mean_values=newcolumns['Revised Cost'].mean()
newcolumns['Revised Cost']=newcolumns['Revised Cost'].fillna(mean_values)
#Mode
most_frequent_values=newcolumns['Zipcode'].mode()[0]
newcolumns['Zipcode']=newcolumns['Zipcode'].fillna(most_frequent_values)

In [27]:
#print the colun to make sure that have filled the missing values correctly:
print(newcolumns)

        Zipcode   Revised Cost
0       94102.0    4000.000000
1       94102.0     500.000000
2       94109.0  132856.186492
3       94109.0    2000.000000
4       94102.0  100000.000000
...         ...            ...
198895  94110.0       1.000000
198896  94110.0    5000.000000
198897  94110.0       1.000000
198898  94110.0       1.000000
198899  94110.0       1.000000

[198900 rows x 2 columns]


# Task 1
Try to handle missing values for categorical valriables?   

In [52]:
#Fill the missing rows for ['Existing Construction Type','Proposed Use'] with the most common category

categorical_columns = mydata_bpermits[['Existing Construction Type','Proposed Use']]

for f in categorical_columns:
    missings = sum(categorical_columns[f].isnull())
    if missings > 0:
        vars_with_missing.append(f)
        missings_perc = missings/mydata_bpermits.shape[0]

        print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))


most_frequent_values = categorical_columns['Existing Construction Type'].mode()[0]
newcolumns['Existing Construction Type'] = categorical_columns['Existing Construction Type'].fillna(most_frequent_values)

most_frequent_values = categorical_columns['Proposed Use'].mode()[0]
newcolumns['Proposed Use'] = categorical_columns['Proposed Use'].fillna(most_frequent_values)

#Repeat the same for other missing categorical columns with


Variable Existing Construction Type has 43366 records (21.80%) with missing values
Variable Proposed Use has 42439 records (21.34%) with missing values


In [53]:
print(newcolumns)
vars_with_missing = []
missings = 0
missings_perc = 0

#Check the changes after handling missing categorical values. If no output means, no missing values in data. 
for f in newcolumns:
    missings = sum(newcolumns[f].isnull())
    vars_with_missing.append(f)
    missings_perc = missings/mydata_bpermits.shape[0]
    print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))


        Zipcode   Revised Cost  Existing Construction Type       Proposed Use
0       94102.0    4000.000000                         3.0  1 family dwelling
1       94102.0     500.000000                         3.0  1 family dwelling
2       94109.0  132856.186492                         1.0       retail sales
3       94109.0    2000.000000                         5.0  1 family dwelling
4       94102.0  100000.000000                         3.0  1 family dwelling
...         ...            ...                         ...                ...
198895  94110.0       1.000000                         5.0  1 family dwelling
198896  94110.0    5000.000000                         5.0         apartments
198897  94110.0       1.000000                         5.0  1 family dwelling
198898  94110.0       1.000000                         5.0  1 family dwelling
198899  94110.0       1.000000                         5.0  1 family dwelling

[198900 rows x 4 columns]
Variable Zipcode has 0 records (0.00%

### Interpolation 
We intend to inerpolate some of the missing values 'NaN' by interpolation.

In [54]:
#we copy the two columns again..
newcolumns=mydata_bpermits[['Zipcode','Revised Cost']]

#here we use a magic:)  'df.interpolade()' function.
newcolumns['Revised Cost']=newcolumns['Revised Cost'].interpolate()

#try to see what happened
print(newcolumns['Revised Cost'])

#interpolation function has other parameters which you can use based on your problem..
#For example, by default the function is linear, but you can change it to polynominal, pad, etc. You can find 
#more info here: https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.DataFrame.interpolate.html  

0           4000.0
1            500.0
2           1250.0
3           2000.0
4         100000.0
            ...   
198895         1.0
198896      5000.0
198897         1.0
198898         1.0
198899         1.0
Name: Revised Cost, Length: 198900, dtype: float64


#### Binning the data
In this part, we try to handle noisy data by binning method. 
Here is an example of "ticket price". As we dicsucsed during the class, sort the data: 4,8,15,21,21,24,25,28,34 , and then: 

1. Binning with Mean:
    - Bin1: 9,9,9
    - Bin2: 22,22,22
    - Bin3: 29,29,29

2. Binning with Boundaries:

    - Bin1: 4,4,15
    - Bin2: 21,21,24
    - Bin3: 25,25,34
    
3. Binning with Median:

    - Bin1: 8,8,8
    - Bin2: 21,21,21
    - Bin3: 28,28,28


##### Instruction:
Follow the below to do so:
1. Import the iris data set:
1. Sort the array of given data set.
2. Divide the range into N (in this case 5) intervals, each containing the approximately same number of samples(Equal-depth    
   partitioning).
3. Store mean/ median/ boundaries in each row.
First import the data and select only one column to apply your binding methods:

In [91]:
import xlrd
import csv
import numpy as np   
import math 
import pandas as pd
from sklearn.datasets import load_iris 
from sklearn import datasets, linear_model, metrics  
#importing the data
mydata_iris=pd.read_csv('lab2_data/iris.csv')
mydata_iris.describe()

a = np.array(mydata_iris.iloc[:,2])
b = np.zeros(150) 
  
 
b=np.sort(a)  #sort the array 
  
# we decided to have three bins
bin1=np.zeros((30,5))  
bin2=np.zeros((30,5)) 
bin3=np.zeros((30,5)) 

In [97]:
b[1]

2.2

#Binning with Mean:

In [58]:

  
# Binning with mean 
for i in range (0,150,5): 
    k=int(i/5) 
    mean=(b[i] + b[i+1] + b[i+2] + b[i+3] + b[i+4])/5
    for j in range(5): 
        bin1[k,j]=mean 
print("Bin Mean: \n",bin1) 
     


Bin Mean: 
 [[2.18 2.18 2.18 2.18 2.18]
 [2.34 2.34 2.34 2.34 2.34]
 [2.48 2.48 2.48 2.48 2.48]
 [2.52 2.52 2.52 2.52 2.52]
 [2.62 2.62 2.62 2.62 2.62]
 [2.7  2.7  2.7  2.7  2.7 ]
 [2.74 2.74 2.74 2.74 2.74]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.86 2.86 2.86 2.86 2.86]
 [2.9  2.9  2.9  2.9  2.9 ]
 [2.96 2.96 2.96 2.96 2.96]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.04 3.04 3.04 3.04 3.04]
 [3.1  3.1  3.1  3.1  3.1 ]
 [3.1  3.1  3.1  3.1  3.1 ]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.24 3.24 3.24 3.24 3.24]
 [3.32 3.32 3.32 3.32 3.32]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.48 3.48 3.48 3.48 3.48]
 [3.56 3.56 3.56 3.56 3.56]
 [3.74 3.74 3.74 3.74 3.74]
 [3.82 3.82 3.82 3.82 3.82]
 [4.12 4.12 4.12 4.12 4.12]]


#Binning with Boundaries:

In [98]:
# Bin boundaries 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        if (b[i+j]-b[i]) < (b[i+4]-b[i+j]): 
            bin2[k,j]=b[i] 
        else: 
            bin2[k,j]=b[i+4]        
print("Bin Boundaries: \n",bin2) 
  



Bin Boundaries: 
 [[2.  2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.4 2.4]
 [2.4 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.6]
 [2.6 2.6 2.6 2.6 2.7]
 [2.7 2.7 2.7 2.7 2.7]
 [2.7 2.7 2.7 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.3 3.3]
 [3.3 3.3 3.3 3.3 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.6 3.6 3.6]
 [3.7 3.7 3.7 3.8 3.8]
 [3.8 3.8 3.8 3.8 3.9]
 [3.9 3.9 3.9 4.4 4.4]]


#Binning with Median:

In [99]:
# Bin median 
for i in range (0,150,5): 
    k=int(i/5) 
    for j in range (5): 
        bin3[k,j]=b[i+2] 
print("Bin Median: \n",bin3) 

Bin Median: 
 [[2.2 2.2 2.2 2.2 2.2]
 [2.3 2.3 2.3 2.3 2.3]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.6 2.6 2.6 2.6 2.6]
 [2.7 2.7 2.7 2.7 2.7]
 [2.7 2.7 2.7 2.7 2.7]
 [2.8 2.8 2.8 2.8 2.8]
 [2.8 2.8 2.8 2.8 2.8]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.2 3.2 3.2 3.2 3.2]
 [3.3 3.3 3.3 3.3 3.3]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.5 3.5 3.5 3.5 3.5]
 [3.6 3.6 3.6 3.6 3.6]
 [3.7 3.7 3.7 3.7 3.7]
 [3.8 3.8 3.8 3.8 3.8]
 [4.1 4.1 4.1 4.1 4.1]]


### Normalization
#### Min-MaxScaler metod:
The data transformation is given by:

feature_std = (feature_x - feature_x.min(axis=0)) / (feature_x.max(axis=0) - feature_x.min(axis=0))
feature_scaled = feature_std * (max - min) + min

You can use the folwoing librry to do the normalization automatically:

#from sklearn import preprocessing
#min_max_scaler = preprocessing.MinMaxScaler()
#min_max_scaler.fit_transform('your data')
#min_max_scaler.fit_transform('your data')



## Task 2
Try to implement the normalization method on the iris data:


In [134]:
""" TODO:
Your code should be placed here...
"""
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

features = np.array(mydata_iris.iloc[:,1:5])

print("Before Min Max Normalization - SepalLengthCm	SepalWidthCm	PetalLengthCm	PetalWidthCm")
print(features)

normalized_feature_width = min_max_scaler.fit_transform(features)
print("After Normalization")
print(normalized_feature_width)


Before Min Max Normalization - SepalLengthCm	SepalWidthCm	PetalLengthCm	PetalWidthCm
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5

### Import the Australian weather data set
 

In [135]:
#importing the NSL-KDD data
mydata_weather = pd.read_csv('lab2_data/weatherAUS.csv',low_memory=False)
print(mydata_weather.shape)
mydata_weather.head(5)

(142193, 24)


Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

### Data Conversion-
#### Using Factorize, Label and One-hot Encding
Factorization is a method that we can convert categoricsl data to numericl. This is usefull when your e.g., feature selection algorithm does not support categorical data. SO in this way first, you can transfer your data to numerical, then you can send it to feature selection function to select the most informative attributes. Below you see a very simple example of factoriztion:   



In [136]:
accomodation_data = ["Location","WindGustDir", "WindDir9am"]
num_data, meta_data = pd.factorize(accomodation_data)
print(meta_data)
print(num_data)

['Location' 'WindGustDir' 'WindDir9am']
[0 1 2]


In [137]:
#Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


In [141]:
#you can use one-hot encoding 
print('old shape:', mydata_weather.shape)
new_data=pd.get_dummies(mydata_weather['Location'])
new_column_names=new_data.columns
print(new_column_names)
print(new_data)
new_mydata_weather=mydata_weather.copy()
new_mydata_weather[new_column_names]=new_data

print('new shape:', new_mydata_weather.shape)
print(new_mydata_weather)

old shape: (142193, 24)
Index(['Adelaide', 'Albany', 'Albury', 'AliceSprings', 'BadgerysCreek',
       'Ballarat', 'Bendigo', 'Brisbane', 'Cairns', 'Canberra', 'Cobar',
       'CoffsHarbour', 'Dartmoor', 'Darwin', 'GoldCoast', 'Hobart',
       'Katherine', 'Launceston', 'Melbourne', 'MelbourneAirport', 'Mildura',
       'Moree', 'MountGambier', 'MountGinini', 'Newcastle', 'Nhil',
       'NorahHead', 'NorfolkIsland', 'Nuriootpa', 'PearceRAAF', 'Penrith',
       'Perth', 'PerthAirport', 'Portland', 'Richmond', 'Sale', 'SalmonGums',
       'Sydney', 'SydneyAirport', 'Townsville', 'Tuggeranong', 'Uluru',
       'WaggaWagga', 'Walpole', 'Watsonia', 'Williamtown', 'Witchcliffe',
       'Wollongong', 'Woomera'],
      dtype='object')
        Adelaide  Albany  Albury  AliceSprings  BadgerysCreek  Ballarat  \
0              0       0       1             0              0         0   
1              0       0       1             0              0         0   
2              0       0       1      

In [146]:
#you can use label_encoder.fit_transform() function
mydata_weather['Location']= label_encoder.fit_transform(mydata_weather['Location'])
print(mydata_weather['Location'])

0          2
1          2
2          2
3          2
4          2
          ..
142188    41
142189    41
142190    41
142191    41
142192    41
Name: Location, Length: 142193, dtype: int64


## Task 3
In this task you work on the "nsl-kdd-original" data. The data set containes numerical and categorical featurees. You need to check whether it contains missing values or noisy data, if yes try to handle them. You may need to convert the categoricall data to numericall, so you can use it (later) in the modeling part. This is because some of the classifiers can not suport categroical varaibles. When you have done use the feature selection function to select the most informative features. In the next lab, you will visualize this prepared data.  

### Feature Selection
In this part, there is a function called "feature_importance()" which is responsible to select the most 'n' important features from the given data. 
At this point, it is not necessary to undrstand the feature_importance function. You just need to call the function with the data select the n top feasture. You can tune the numeber of top features to se what will happen. 



In [148]:
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt

def feature_importance(mydata,top_featurs):
    print('feature_selection_IMP started...')
    X=mydata.copy()
    y=X['label']
    #X=X.drop(['target','biweek_send_date','t_chassis'],axis=1).copy()
    
    model = ExtraTreesClassifier(n_estimators=100)
    model.fit(X,y)
    model.feature_importances_ #use inbuilt class feature_importances of tree based classifiers
    
    #plot graph of feature importances for better visualization
    feat_importances = pd.Series(model.feature_importances_, index=X.columns)
    #mc=feat_importances.nlargest(30).plot(kind='barh')
    mc=feat_importances.nlargest(top_featurs).index
    selected_column=np.array(mc)
    plt.show()
    # Fit, Format, and Return
    return selected_column

In [149]:
#importing the original data with categorical data
mydata_NSL_KDD = pd.read_csv('lab2_data/nsl-kdd-original.csv',low_memory=False)
mydata_NSL_KDD.head()
print(mydata_NSL_KDD.shape)

(175341, 45)


In [152]:
print(mydata_NSL_KDD.head())
mydata_bpermits=mydata_NSL_KDD.copy()


vars_with_missing = []

for f in mydata_bpermits.columns:
    #missings = mydata[f].isnull().count()
    missings = sum(mydata_bpermits[f].isnull())
    if missings > 0:
        vars_with_missing.append(f)
        missings_perc = missings/mydata_bpermits.shape[0]
        
        print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))
        
print('In total, there are {} variables with missing values'.format(len(vars_with_missing)))

   id       dur proto service state  spkts  dpkts  sbytes  dbytes       rate  \
0   1  0.121478   tcp       -   FIN      6      4     258     172  74.087490   
1   2  0.649902   tcp       -   FIN     14     38     734   42014  78.473372   
2   3  1.623129   tcp       -   FIN      8     16     364   13186  14.170161   
3   4  1.681642   tcp     ftp   FIN     12     12     628     770  13.677108   
4   5  0.449454   tcp       -   FIN     10      6     534     268  33.373826   

   ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  \
0  ...                 1               1             0           0   
1  ...                 1               2             0           0   
2  ...                 1               3             0           0   
3  ...                 1               3             1           1   
4  ...                 1              40             0           0   

   ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  attack_cat  \
0                 0   

In [163]:
mydata_NSL_KDD.head()

""" TODO:
1. fix the missing values
2. convert and normalize the values


Your code should be placed here...

3. using the below code you can call the feature selection function and select the 15 most important features
#Note: There is error with the auto feature selection code as it throws exception for non numerical rows

#top_featurs=15
#Sending the full data to the feature selection function
#selected_features=feature_importance(mydata_NSL_KDD,top_featurs)
#mydata_NSL_KDD=mydata_NSL_KDD[selected_features]
#print('selected features: ',mydata_NSL_KDD.columns)

Your code should be placed here...

"""
#1. There are no missing values/ blanks as per the output 
mydata_bpermits=mydata_NSL_KDD.copy()


vars_with_missing = []

for f in mydata_bpermits.columns:
    #missings = mydata[f].isnull().count()
    missings = sum(mydata_bpermits[f].isnull())
    if missings > 0:
        vars_with_missing.append(f)
        missings_perc = missings/mydata_bpermits.shape[0]
        
        print('Variable {} has {} records ({:.2%}) with missing values'.format(f, missings, missings_perc))
        
print('In total, there are {} variables with missing values'.format(len(vars_with_missing)))

#2. #Normalization of Numerical Values

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

#select the top 15 numerical features manually
features = np.array(mydata_NSL_KDD.loc[:,['dur','spkts','dpkts','sbytes','dbytes','rate','sttl','dttl','sload','dload','sloss','dloss','sinpkt','dinpkt','sjit']])

print("Before normalization")
print(features)

normalized_feature_width = min_max_scaler.fit_transform(features)
print("After Normalization")
print(normalized_feature_width)

#3. using the below code you can call the feature selection function and select the 15 most important features
#Note: There is error with the auto feature selection code as it throws exception for non numerical rows, e.g, 'tcp'

In total, there are 0 variables with missing values
Before normalization
[[1.21478000e-01 6.00000000e+00 4.00000000e+00 ... 2.42956000e+01
  8.37500000e+00 3.01775470e+01]
 [6.49902000e-01 1.40000000e+01 3.80000000e+01 ... 4.99150000e+01
  1.54328650e+01 6.14269340e+01]
 [1.62312900e+00 8.00000000e+00 1.60000000e+01 ... 2.31875571e+02
  1.02737203e+02 1.71795869e+04]
 ...
 [9.00000000e-06 2.00000000e+00 0.00000000e+00 ... 9.00000000e-03
  0.00000000e+00 0.00000000e+00]
 [9.00000000e-06 2.00000000e+00 0.00000000e+00 ... 9.00000000e-03
  0.00000000e+00 0.00000000e+00]
 [9.00000000e-06 2.00000000e+00 0.00000000e+00 ... 9.00000000e-03
  0.00000000e+00 0.00000000e+00]]
After Normalization
[[2.02463370e-03 5.20020801e-04 3.64497904e-04 ... 2.87959811e-04
  1.47663416e-04 2.06627593e-05]
 [1.08317020e-02 1.35205408e-03 3.46273009e-03 ... 5.91609754e-04
  2.72103829e-04 4.20594143e-05]
 [2.70521550e-02 7.28029121e-04 1.45799162e-03 ... 2.74826905e-03
  1.81140614e-03 1.17629729e-02]
 ...
 [1.5

<div class="alert alert-block alert-danger">

__IMPORTANT__ 

Please complete this Jupyter Notebook file and upload it in the Blackboard before the deadline.

</div>

## Aung Naing Oo